# Generated by Django 4.1.13 on 2024-02-02 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastWeatherDataEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(max_length=3)),
                ('atmospheric_pressure', models.FloatField(max_length=3)),
                ('moisture', models.FloatField(max_length=3)),
                ('percentage_precipitation', models.FloatField(max_length=3)),
                ('weather_condition', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'forecast_weather_data_entity',
            },
        ),
        migrations.CreateModel(
            name='RealWeatherDataEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(max_length=3)),
                ('atmospheric_pressure', models.FloatField(max_length=3)),
                ('moisture', models.FloatField(max_length=3)),
                ('percentage_precipitation', models.FloatField(max_length=3)),
                ('weather_condition', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'real_weather_data_entity',
            },
        ),
    ]
